name: Build MRS

on:
  push:
    paths:
      - "rules/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Mihomo
      run: |
        wget -q https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64
        chmod +x mihomo-linux-amd64
        sudo mv mihomo-linux-amd64 /usr/local/bin/mihomo

    - name: Create mrs dir
      run: mkdir -p mrs

    - name: Convert rules
      run: |
        for file in rules/*.yaml; do
          name=$(basename "$file" .yaml)

          if grep -q "IP-CIDR" "$file"; then
            type="ipcidr"
          else
            type="domain"
          fi

          mihomo convert-ruleset $type yaml "$file" "mrs/$name.mrs"
        done

    - name: Commit
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add mrs/*.mrs
        git commit -m "Auto build MRS" || echo "No changes"
        git push
