name: Lint Rules

on:
  pull_request:
  push:
    paths:
      - "rules/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install yamllint
      run: pip install yamllint

    - name: Check yaml
      # 使用 | 告诉 YAML 解析器把下面这行当成纯文本执行
      run: |
        yamllint -d "{extends: default, rules: {document-start: disable, line-length: disable, new-line-at-end-of-file: disable}}" rules
